name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.8"
      - run: julia --project -e 'using Pkg; Pkg.test()'
      - run: julia --project examples/xor.jl
      - run: julia --project examples/spiral.jl
